# Generated by Django 4.0.5 on 2022-06-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_phone_number_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_logo',
            new_name='hood_pic',
        ),
    ]
