# Generated by Django 4.0.5 on 2022-06-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_hood_logo_neighbourhood_hood_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_pic',
            new_name='hood_logo',
        ),
    ]
